-- Migration: seed the crops catalog with common fruits, vegetables, herbs,
-- and flowers so a freshly-provisioned environment has a usable picker out
-- of the gate without depending on the optional OpenFarm bulk import.
--
-- Idempotent: each row upserts on slug. Re-running this migration overwrites
-- the curated columns (common_name, scientific_name, category, source_*)
-- with the values defined here, claiming these slugs as internal_seed rows
-- even if a prior bulk import already populated them.

insert into crops (slug, common_name, scientific_name, category, source_provider, attribution_text)
values
  -- Vegetables
  ('tomato',            'Tomato',            'Solanum lycopersicum',                    'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('carrot',            'Carrot',            'Daucus carota',                           'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('lettuce',           'Lettuce',           'Lactuca sativa',                          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cucumber',          'Cucumber',          'Cucumis sativus',                         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('bell-pepper',       'Bell Pepper',       'Capsicum annuum',                         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('hot-pepper',        'Hot Pepper',        'Capsicum annuum',                         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('onion',             'Onion',             'Allium cepa',                             'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('garlic',            'Garlic',            'Allium sativum',                          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('shallot',           'Shallot',           'Allium cepa var. aggregatum',             'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('leek',              'Leek',              'Allium ampeloprasum',                     'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('potato',            'Potato',            'Solanum tuberosum',                       'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('sweet-potato',      'Sweet Potato',      'Ipomoea batatas',                         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('broccoli',          'Broccoli',          'Brassica oleracea var. italica',          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cauliflower',       'Cauliflower',       'Brassica oleracea var. botrytis',         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cabbage',           'Cabbage',           'Brassica oleracea var. capitata',         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('brussels-sprouts',  'Brussels Sprouts',  'Brassica oleracea var. gemmifera',        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('kale',              'Kale',              'Brassica oleracea var. sabellica',        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('kohlrabi',          'Kohlrabi',          'Brassica oleracea var. gongylodes',       'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('bok-choy',          'Bok Choy',          'Brassica rapa subsp. chinensis',          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('turnip',            'Turnip',            'Brassica rapa subsp. rapa',               'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('radish',            'Radish',            'Raphanus sativus',                        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('arugula',           'Arugula',           'Eruca vesicaria',                         'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('spinach',           'Spinach',           'Spinacia oleracea',                       'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('swiss-chard',       'Swiss Chard',       'Beta vulgaris subsp. cicla',              'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('beet',              'Beet',              'Beta vulgaris',                           'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('zucchini',          'Zucchini',          'Cucurbita pepo',                          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('summer-squash',     'Summer Squash',     'Cucurbita pepo',                          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('winter-squash',     'Winter Squash',     'Cucurbita maxima',                        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('butternut-squash',  'Butternut Squash',  'Cucurbita moschata',                      'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('pumpkin',           'Pumpkin',           'Cucurbita pepo',                          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('eggplant',          'Eggplant',          'Solanum melongena',                       'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('green-bean',        'Green Bean',        'Phaseolus vulgaris',                      'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('snap-pea',          'Snap Pea',          'Pisum sativum var. macrocarpon',          'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('shelling-pea',      'Shelling Pea',      'Pisum sativum',                           'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('sweet-corn',        'Sweet Corn',        'Zea mays var. saccharata',                'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('celery',            'Celery',            'Apium graveolens',                        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('asparagus',         'Asparagus',         'Asparagus officinalis',                   'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('artichoke',         'Artichoke',         'Cynara cardunculus var. scolymus',        'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('okra',              'Okra',              'Abelmoschus esculentus',                  'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),
  ('rhubarb',           'Rhubarb',           'Rheum rhabarbarum',                       'vegetable', 'internal_seed', 'Olivia''s Garden curated catalog'),

  -- Fruits
  ('strawberry',        'Strawberry',        'Fragaria x ananassa',                     'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('blueberry',         'Blueberry',         'Vaccinium corymbosum',                    'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('raspberry',         'Raspberry',         'Rubus idaeus',                            'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('blackberry',        'Blackberry',        'Rubus fruticosus',                        'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('apple',             'Apple',             'Malus domestica',                         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('pear',              'Pear',              'Pyrus communis',                          'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('peach',             'Peach',             'Prunus persica',                          'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('nectarine',         'Nectarine',         'Prunus persica var. nucipersica',         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('plum',              'Plum',              'Prunus domestica',                        'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cherry',            'Cherry',            'Prunus avium',                            'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('apricot',           'Apricot',           'Prunus armeniaca',                        'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('fig',               'Fig',               'Ficus carica',                            'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('grape',             'Grape',             'Vitis vinifera',                          'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('watermelon',        'Watermelon',        'Citrullus lanatus',                       'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cantaloupe',        'Cantaloupe',        'Cucumis melo var. cantalupensis',         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('honeydew',          'Honeydew Melon',    'Cucumis melo var. inodorus',              'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('lemon',             'Lemon',             'Citrus limon',                            'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('lime',              'Lime',              'Citrus aurantiifolia',                    'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('orange',            'Orange',            'Citrus sinensis',                         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('grapefruit',        'Grapefruit',        'Citrus paradisi',                         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('mandarin',          'Mandarin Orange',   'Citrus reticulata',                       'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('avocado',           'Avocado',           'Persea americana',                        'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('pomegranate',       'Pomegranate',       'Punica granatum',                         'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('persimmon',         'Persimmon',         'Diospyros kaki',                          'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('mulberry',          'Mulberry',          'Morus nigra',                             'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('elderberry',        'Elderberry',        'Sambucus nigra',                          'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),
  ('currant',           'Currant',           'Ribes rubrum',                            'fruit',     'internal_seed', 'Olivia''s Garden curated catalog'),

  -- Herbs
  ('basil',             'Basil',             'Ocimum basilicum',                        'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('parsley',           'Parsley',           'Petroselinum crispum',                    'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cilantro',          'Cilantro',          'Coriandrum sativum',                      'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('mint',              'Mint',              'Mentha spicata',                          'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('rosemary',          'Rosemary',          'Salvia rosmarinus',                       'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('thyme',             'Thyme',             'Thymus vulgaris',                         'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('sage',              'Sage',              'Salvia officinalis',                      'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('oregano',           'Oregano',           'Origanum vulgare',                        'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('chives',            'Chives',            'Allium schoenoprasum',                    'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('dill',              'Dill',              'Anethum graveolens',                      'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('tarragon',          'Tarragon',          'Artemisia dracunculus',                   'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('lemon-balm',        'Lemon Balm',        'Melissa officinalis',                     'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),
  ('chamomile',         'Chamomile',         'Matricaria chamomilla',                   'herb',      'internal_seed', 'Olivia''s Garden curated catalog'),

  -- Flowers
  ('sunflower',         'Sunflower',         'Helianthus annuus',                       'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('marigold',          'Marigold',          'Tagetes erecta',                          'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('zinnia',            'Zinnia',            'Zinnia elegans',                          'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('cosmos',            'Cosmos',            'Cosmos bipinnatus',                       'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('petunia',           'Petunia',           'Petunia x atkinsiana',                    'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('pansy',             'Pansy',             'Viola x wittrockiana',                    'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('daisy',             'Daisy',             'Bellis perennis',                         'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('geranium',          'Geranium',          'Pelargonium x hortorum',                  'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('begonia',           'Begonia',           'Begonia x semperflorens-cultorum',        'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('impatiens',         'Impatiens',         'Impatiens walleriana',                    'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('snapdragon',        'Snapdragon',        'Antirrhinum majus',                       'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('nasturtium',        'Nasturtium',        'Tropaeolum majus',                        'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('sweet-pea',         'Sweet Pea',         'Lathyrus odoratus',                       'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('black-eyed-susan',  'Black-Eyed Susan',  'Rudbeckia hirta',                         'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('coneflower',        'Coneflower',        'Echinacea purpurea',                      'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('hollyhock',         'Hollyhock',         'Alcea rosea',                             'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('foxglove',          'Foxglove',          'Digitalis purpurea',                      'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('dahlia',            'Dahlia',            'Dahlia pinnata',                          'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('calendula',         'Calendula',         'Calendula officinalis',                   'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('morning-glory',     'Morning Glory',     'Ipomoea purpurea',                        'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('lavender',          'Lavender',          'Lavandula angustifolia',                  'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('rose',              'Rose',              'Rosa',                                    'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('tulip',             'Tulip',             'Tulipa',                                  'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('daffodil',          'Daffodil',          'Narcissus pseudonarcissus',               'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('iris',              'Iris',              'Iris germanica',                          'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('peony',             'Peony',             'Paeonia lactiflora',                      'flower',    'internal_seed', 'Olivia''s Garden curated catalog'),
  ('hibiscus',          'Hibiscus',          'Hibiscus rosa-sinensis',                  'flower',    'internal_seed', 'Olivia''s Garden curated catalog')
on conflict (slug) do update set
  common_name       = excluded.common_name,
  scientific_name   = excluded.scientific_name,
  category          = excluded.category,
  source_provider   = excluded.source_provider,
  attribution_text  = excluded.attribution_text,
  updated_at        = now();
